---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.2.1
  - pip install ansible-lint

  # Add ansible.cfg to pick up roles path.
  # - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - ansible-playbook -i localhost, playbook.yml --syntax-check
  - ansible-lint playbook.yml -x ANSIBLE0002

cache:
  directories:
  - /home/travis/virtualenv/python2.7.12/lib/python2.7/
